project:
  type: website
  output-dir: doc

website:
  title: "Pollen Deposition Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Report
      - href: workflow.qmd
        text: Workflow

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
